In [3]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

In [4]:
DIR= '/home/nagarakshitha/Desktop/A'
categories=['busy', 'free']

for category in categories:
    path = os.path.join(DIR,category)
    for img in os.listdir(path):
        img_array=cv2.imread(os.path.join(path,img), cv2.IMREAD_COLOR)
        #plt.imshow(img_array)
        #plt.show()


'for category in categories:\n    path_test = os.path.join(DIR_test,category)\n    for img in os.listdir(path_test):\n        img_array_test=cv2.imread(os.path.join(path,img), cv2.IMREAD_COLOR)'

In [5]:
training_data=[]


def create_training_data():
    for category in categories:
        path = os.path.join(DIR,category)
        class_num=categories.index(category)
        for img in os.listdir(path):
            img_array=cv2.imread(os.path.join(path,img))
            img_array=cv2.resize(img_array,(32,32))
            training_data.append([img_array, class_num])

        
create_training_data()


print(len(training_data))  

10952


In [6]:
import random
random.shuffle(training_data)

random.shuffle(test_data)

In [7]:
X = []
y = []

X_test=[]
y_test=[]

IMG_SIZE=32
for features,label in training_data:
    X.append(features)
    y.append(label)



#print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 3))
y=np.array(y)
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 3)
print(np.shape(X))

(10952, 32, 32, 3)


In [10]:
print(X[0])
np.shape(X)

[[[110 130 131]
  [109 129 130]
  [109 129 130]
  ...
  [ 92 111 114]
  [ 92 112 114]
  [ 83 110 112]]

 [[112 132 133]
  [109 129 130]
  [107 127 128]
  ...
  [118 137 140]
  [116 136 138]
  [114 139 141]]

 [[110 130 131]
  [108 128 129]
  [109 129 130]
  ...
  [ 99 118 121]
  [106 125 128]
  [112 134 135]]

 ...

 [[ 89  94  91]
  [ 89  94  91]
  [ 80  85  82]
  ...
  [ 74  91  90]
  [ 81  99  98]
  [ 95 113 114]]

 [[ 90  95  96]
  [ 91  96  97]
  [ 75  82  82]
  ...
  [ 68  86  85]
  [ 81  99  98]
  [120 138 139]]

 [[ 72  78  77]
  [ 70  78  77]
  [ 55  67  65]
  ...
  [ 95 111 110]
  [113 129 131]
  [123 142 145]]]


(10952, 32, 32, 3)

In [12]:

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,Activation, Flatten, Conv2D, MaxPool2D
import pickle

pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

#Normalizing data
X=np.array(X)
X=X/255.0

model = Sequential()

model.add(Conv2D(input_shape=(32,32,3),filters=32,kernel_size=(3,3), activation="relu"))
model.add(Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))

model.add(Conv2D(filters=64, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=64, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))

model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))

model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=(2,2)))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])
model.fit(X, y, batch_size=10, epochs=3, validation_split=0.2)
model.summary()

Train on 8761 samples, validate on 2191 samples
Epoch 1/3
8761/8761 [==============================] - 66s 8ms/sample - loss: 0.3335 - accuracy: 0.8693 - val_loss: 0.5754 - val_accuracy: 0.6326
Epoch 2/3
8761/8761 [==============================] - 61s 7ms/sample - loss: 0.1276 - accuracy: 0.9587 - val_loss: 0.2551 - val_accuracy: 0.9083
Epoch 3/3
8761/8761 [==============================] - 57s 6ms/sample - loss: 0.0881 - accuracy: 0.9706 - val_loss: 0.0537 - val_accuracy: 0.9804
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 30, 30, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 64)        0         
________________________________